name: Access ID
on:
  pull_request:
    branches:
      - '*'

env:
  ACCESS_ID: ${{ vars.ACCESS_ID }}
jobs:
  setupPython:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Print Access ID
        run: echo "The ACCESS_ID is $ACCESS_ID"
