name: Access ID
on:
  push:
    branches:
      - '*'
jobs:
  setupPython:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Access ID
        run: echo "ACCESS_ID: ${{ vars.ACCESS_ID }}"
