name: Setting up python environment
on:
  pull_request:
    branches:
      - '*'
jobs:
  setupPython:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest flake8
      - name: Check Python Version
        run: python --version
      - name: Run Flake8 Linting
        run: flake8 --version
      - name: Run Pytest
        run: pytest --version
