name: secret use case
on:
  pull_request:
    branches:
      - '*'
jobs:
  secretSetup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Secret (Simulated API call)
        env:
          API_SECRET: ${{ secrets.SECRET }}
        run: |
          # Simulate an API call using the secret.
          # Important: Do NOT echo or print the secret directly.
          # Instead, use it in a command or script that doesn't output it to logs.
          # Example using curl (replace with your actual API call):
          curl -X POST -H "Authorization: Bearer $API_SECRET" -H "Content-Type: application/json" -d '{"message": "test"}' https://example.com/api/some_endpoint > /dev/null 2>&1
          # The > /dev/null 2>&1 redirects both standard output and standard error
          # to /dev/null, effectively silencing the output.
      
