name: secret use case
on:
  push:
    branches:
      - '*'
env:
  SECRET: ${{ secrets.SECRET }}
jobs:
  secretSetup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Secret (Simulated API call)
        run: echo "the secret is $SECRET"
      
